"""Add VerifiedSeller modeld

Revision ID: bfcfba407e10
Revises: 8305cc9cc856
Create Date: 2025-11-25 11:32:36.147987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcfba407e10'
down_revision = '8305cc9cc856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('farm_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('farm_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('farm_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('farming_experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('crops_grown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('id_proof_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_seller', schema=None) as batch_op:
        batch_op.drop_column('verified_date')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('id_proof_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('crops_grown')
        batch_op.drop_column('farming_experience')
        batch_op.drop_column('farm_size')
        batch_op.drop_column('farm_location')
        batch_op.drop_column('farm_name')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
